---
title: "EDLD651_final_project"
author: "Kyla & Erika & Cheyna"
format: pdf
editor: visual
---

# Load Packages

```{r}
library(here)
library(janitor)
library(rio)
library(tidyverse)
library(tm)
```

# Import Data

```{r}
# Fruit data
fruit_files <- list.files(pattern = ".xlsx", path = "../data/fruit-2020", full.names = TRUE)

fruit_2020 <- do.call(rbind, lapply
        (fruit_files, import, as.is=T, header = FALSE))

# Vegetable Data
veg_files <- list.files(pattern = ".xlsx", path = "../data/vegetables-2020", full.names = TRUE)

veg_2020 <- do.call(rbind, lapply
        (veg_files, import, as.is=T, header = FALSE))
```

# Removing rows without data

```{r}
# Fruit cleaning
fruit_2020 <- fruit_2020 %>% # rename cols to be more descriptive
  rename(fruit = ...1, retail_price = ...2, retail_price_unit = ...3, yield = ...4, cup_eq_size = ...5, cup_eq_unit = ...6,cup_eq_price = ...7)

fruit_2020_clean <- fruit_2020 %>% # remove rows without data (these were just the citation of where the data came from)
  filter(!substr(fruit, 1, 1) == "1") %>% 
  filter(!substr(fruit, 1, 1) == "2") %>% 
  filter(!substr(fruit, 1, 1) == "3") %>% 
  filter(!substr(fruit, 1, 1) == "4") %>% 
  filter(!substr(fruit, 1, 6) == "Source")

# Veggie cleaning
veg_2020 <- veg_2020 %>% # rename cols to be more descriptive
  rename(veg = ...1, retail_price = ...2, retail_price_unit = ...3, yield = ...4, cup_eq_size = ...5, cup_eq_unit = ...6,cup_eq_price = ...7)

veg_2020_clean <- veg_2020 %>% # remove rows without data (these were just the citation of where the data came from)
  filter(!substr(veg, 1, 1) == "1") %>% 
  filter(!substr(veg, 1, 1) == "2") %>% 
  filter(!substr(veg, 1, 1) == "3") %>% 
  filter(!substr(veg, 1, 1) == "4") %>% 
  filter(!substr(veg, 1, 6) == "Source")
```

# Tidying the data

```{r}
# Fruit
fruit_names <- c("Apples", "Apricots", "Bananas", "Mixed berries", "Blackberries", "Blueberries", "Cantaloupe", "Cherries", "Clementines", "Cranberries", "Dates", "Figs", "Fruit cocktail", "Grapefruit", "Grapes", "Honeydew melon", "Kiwi", "Mangoes", "Nectarines", "Oranges", "Papaya", "Peaches", "Pears", "Pineapple", "Plums", "Pomegranate", "Raspberries", "Strawberries", "Watermelon") # creating a vector with the fruit names

fruit_2020_clean <- fruit_2020_clean |> 
  # fix the fruit column to isolate the fruit name
  mutate(fruit = str_extract(fruit, "[^—]+")) |> 
  # create a flag for fruit names
  mutate(is_fruit = fruit %in% fruit_names) |> 
  # fill the fruit name down
  mutate(fruit_name = if_else(is_fruit, fruit, NA_character_)) |> 
  fill(fruit_name, .direction = "down") |> 
  # remove rows where fruit column is the fruit name or "Form"
  filter(!is_fruit, fruit != "Form") |> 
  # rename columns
  rename(form = fruit) |> 
  # move the fruit column to the beginning
  relocate(fruit_name, .before = "form") |> 
  # remove the is_fruit column, we don't need it anymore
  select(-is_fruit) |> 
  # remove any rows with NA in the retail_price column
  filter(!is.na(retail_price))

# Vegetable
veg_names <- c("Acorn squash", "Artichoke", "Asparagus", "Avocados", "Beets", "Black beans", "Blackeye peas", "Broccoli", "Brussels sprouts", "Butternut squash", "Cabbage", "Carrots", "Cauliflower", "Celery", "Collard greens", "Sweet corn", "Cucumbers", "Great northern beans", "Green beans", "Green peas", "Green peppers", "Kale", "Kidney beans", "Lentils", "Iceberg lettuce", "Romaine lettuce", "Lima beans", "Mixed vegetables", "Mushrooms", "Mustard greens", "Navy beans", "Okra", "Olives", "Onions", "Pinto beans", "Potatoes", "Pumpkin", "Radish", "Red peppers", "Spinach", "Sweet potatoes", "Tomatoes", "Turnip greens", "Zucchini") # creating a vector with the veggie names

veg_2020_clean <- veg_2020_clean |> 
  # fix the veg column to isolate the veg name
  mutate(veg = str_extract(veg, "[^—]+")) |> 
  # create a flag for veg names
  mutate(is_veg = veg %in% veg_names) |> 
  # fill the veg name down
  mutate(veg_name = if_else(is_veg, veg, NA_character_)) |> 
  fill(veg_name, .direction = "down") |> 
  # remove rows where veg column is the veg name or "Form"
  filter(!is_veg, veg != "Form") |> 
  # rename columns
  rename(form = veg) |> 
  # move the veg column to the beginning
  relocate(veg_name, .before = "form") |> 
  # remove the is_veg column, we don't need it anymore
  select(-is_veg) |> 
  # remove any rows with NA in the reatil_price column
  filter(!is.na(retail_price))
```

# How does the price of fruits and vegetables vary based on form? (Kyla)

```{r}
# remove the numbers at the end of the forms
fruit_2020_clean$form <- removeNumbers(fruit_2020_clean$form)
veg_2020_clean$form <- removeNumbers(veg_2020_clean$form)

# remove additional specifiers from form column that are not important
fruit_2020_clean$form <- gsub("\\s*\\([^\\)]+\\)", "", fruit_2020_clean$form)
fruit_2020_clean$form <- sub(",.*", "", fruit_2020_clean$form)
veg_2020_clean$form <- sub(" .*$", "", veg_2020_clean$form)
veg_2020_clean$form <- gsub(",", "", veg_2020_clean$form)

# change the tomato forms from "Grape", "Roma", and "Large to all be "Fresh"
# and filter to only look at price differences between fresh, frozen, canned, and dried
veg_2020_clean <- veg_2020_clean |> 
  mutate(form = case_when(form == "Canned" ~ "Canned",
                   form == "Grape" ~ "Fresh", 
                   form == "Roma" ~ "Fresh", 
                   form == "Large" ~ "Fresh",
                   TRUE ~ form)) |> 
  filter(form == "Fresh" | form == "Frozen" | form == "Canned" | form == "Dried")

# remove the specific rows for raisins and applesauce because they don't fit cleanly into a category
# and change "Ready to drink" to "Juice"
fruit_2020_clean <- fruit_2020_clean |> 
  filter(form != "Raisins" & form != "Applesauce") |> 
  mutate(form = case_when(form == "Ready to drink" ~ "Juice",
                          TRUE ~ form))

# make sure retail_price is a numeric variable
fruit_2020_clean <- fruit_2020_clean |> 
  mutate(retail_price = as.numeric(retail_price))
veg_2020_clean <- veg_2020_clean |> 
  mutate(retail_price = as.numeric(retail_price))

# examine retail price by form
fruit_summary <- fruit_2020_clean |> 
  group_by(form) |> 
  summarize(mean_retail_price = mean(retail_price, na.rm = TRUE))
veg_summary <- veg_2020_clean |> 
  group_by(form) |> 
  summarize(mean_retail_price = mean(retail_price, na.rm = TRUE))
```

```{r}
fruit_summary |> 
  ggplot(aes(x = form, y = mean_retail_price, fill = form)) +
  geom_bar(stat = "identity") +
  labs(title = "Average Fruit Retail Prices by Form",
       x = "Form",
       y = "Average Retail Price") +
  scale_fill_manual(values = c("#005f73", "#0a9396", "#94d2bd", "#e9d8a6", "#ee9b00", "#ca6702", "#bb3e03")) +
  theme(theme_minimal(),
        legend.position = "NULL",
        axis.text.x = element_text(angle = 45, hjust = 1))

veg_summary |> 
  ggplot(aes(x = form, y = mean_retail_price, fill = form)) +
  geom_bar(stat = "identity") +
  labs(title = "Average Vegetable Retail Prices by Form",
       x = "Form",
       y = "Average Retail Price") +
  scale_fill_manual(values = c("#005f73", "#0a9396", "#94d2bd", "#e9d8a6", "#ee9b00", "#ca6702", "#bb3e03")) +
  theme(theme_minimal(),
        legend.position = "NULL",
        axis.text.x = element_text(angle = 45, hjust = 1))
```


# Do fruit and vegetable prices vary by family (berries, stone fruit etc)? (Erika)

```{r}

```

# What is the relationship between retail price and yield by form? (Cheyna)

```{r}

```
